// @ts-check
import { defineConfig } from 'astro/config';

import react from '@astrojs/react';

import mdx from '@astrojs/mdx';

import icon from 'astro-icon';

// https://astro.build/config
export default defineConfig({
  integrations: [react(), mdx(), icon({
    include: {
      'vscode-icons': [
        'file-type-typescript-official',
        'file-type-js-official',
        'file-type-node2',
        'file-type-python',
        'file-type-go',
        'file-type-csharp',
        'file-type-php',
        'file-type-swift',
        'file-type-reactts',
        'file-type-reactjs',
        'file-type-gatsby',
        'file-type-astro',
        'file-type-svelte',
        'file-type-angular',
        'file-type-vue',
        'file-type-light-next',
        'file-type-light-nx',
        'file-type-css',
        'file-type-scss2',
        'file-type-styled',
        'file-type-tailwind',
        'file-type-test',
        'file-type-jest',
        'file-type-cypress',
        'file-type-playwright',
        'file-type-mongo',
        'file-type-sql',
        'file-type-json',
        'file-type-gitlab',
        'folder-type-github',
        'folder-type-linux',
        'file-type-docker2',
        'file-type-azure',
        'file-type-jenkins',
        'file-type-webpack',
        'file-type-vite',
        'file-type-rest',
        'folder-type-api-opened',
        'file-type-graphql',
        'folder-type-vscode',
        'file-type-nginx',
        'file-type-light-nx',
        'file-type-gradle',
        'file-type-xml',
        'file-type-node',
        'file-type-light-prisma',
        'file-type-pdf2',
        'file-type-babel2'
      ],
      devicon: [
        'java-wordmark',
        'materialui',
        'angularmaterial',
        'bootstrap-wordmark',
        'junit',
        'amazonwebservices-wordmark',
        'intellij',
        'socketio',
        'sqldeveloper',
        'traefikproxy',
        "githubactions",
        "spring",
        "selenium",
        'primeng',
        'githubactions',
        'helm'
      ],
      logos: [
        'react-query-icon',
        'apollostack',
        'leaflet',
        'atlassian',
        'immutable',
        'sequelize',
        'hapi',
        'jquery',
        'laravel',
        'cordova',
        'visual-studio',
        'kubernetes',
        'dotnet',
        'postgresql',
        'subversion',
        'bitbucket',
        'jira',
        'confluence',
        'wordpress-icon',
        'eclipse-icon',
        'xray-for-jira',
        'react',
        'rollup',
        'parcel-icon',
        'grpc',
        'fastapi',
        'openshift',
        'terraform',
        'storyblok-icon',
        'strapi-icon',
        'figma',
        "nestjs"
      ],
      'material-symbols': [
        'stacked-line-chart',
        'grid-4x4',
        'view-kanban-outline',
        'waterfall-chart',
        'accessibility-new',
        'accessibility',
        'download-rounded',
        'mail-outline-rounded',
        'call-outline',
        'dark-mode-outline-rounded',
        'light-mode-outline-rounded'
      ],
      'simple-icons': [
        'oracle',
        'scrumalliance',
        'esbuild',
        'turborepo',
        'mqtt',
        'githubcopilot',
        'anthropic',
        'googlegemini',
        'apachegroovy',
        'apachemaven',
        'flask',
        'jenkins',
        'podman',
        'travisci'
      ],
      'skill-icons': [
        'redux'
      ],
      cib: ['gerrit'],
      'file-icons': ['knockout'],
      iconoir: ['agile'],
      mdi: ['kodi', 'github', 'linkedin']
    }
  })]
});