import { version } from "react";
import {
  authentication,
  buildTools,
  databases,
  ide,
  languages,
  libraries,
  api,
  styling,
  testing,
  tools,
  webserver,
  cicd,
  uiFrameworks,
  cloud,
  container,
  versionControl,
  accessibility,
} from "./technologies";

export const skillsForBundesagentur = [
  languages.typescript,
  languages.csharp,
  languages.nodejs,
  libraries.dotnet,
  libraries.aspnet,
  uiFrameworks.angular,
  databases.sql,
  databases.mssql,
  testing.playwright,
  testing.vitest,
  buildTools.vite,
  buildTools.webpack,
  api.rest,
  cloud.azure,
  authentication.msal,
  ide.vscode,
  ide.visualStudio,
  tools.jira,
  tools.confluence,
  versionControl.github,
  cicd.jenkins,
  cicd.githubActions,
]

export const skillsForDHL = [
  languages.typescript,
  languages.java,
  languages.nodejs,
  databases.sql,
  uiFrameworks.react,
  libraries.reactQuery,
  uiFrameworks.angular,
  styling.primeNg,
  styling.tailwind,
  libraries.spring,
  testing.jest,
  testing.playwright,
  testing.selenium,
  styling.emotion,
  api.rest,
  api.openapi,
  cloud.azure,
  container.docker,
  container.openShift,
  tools.jira,
  tools.confluence,
  ide.intellij,
  versionControl.github,
  webserver.nginx,
  cicd.jenkins,
  cicd.githubActions,
  buildTools.webpack,
  buildTools.vite,
  accessibility.wcag,
  accessibility.aria,
  accessibility.accessibilityTesting,
]

export const skillsForJLA = [
  languages.typescript,
  languages.python,
  languages.nodejs,
  uiFrameworks.react,
  libraries.fastApi,
  styling.emotion,
  api.rest,
  libraries.reactQuery,
  databases.postGresSql,
  cloud.azure,
  authentication.msal,
  ide.vscode,
  api.openapi,
  container.docker,
  cicd.githubActions,
  buildTools.vite
]

export const skillsForPflegeabc = [
  languages.typescript,
  languages.nodejs,
  uiFrameworks.react,
  uiFrameworks.nextjs,
  styling.tailwind,
  libraries.prisma,
  libraries.storyblok,
  libraries.reactPdf,
  databases.sql,
  testing.playwright,
  api.rest,
  tools.jira,
  versionControl.github,
]

export const skillsForRwe = [
  ide.vscode,
  ide.visualStudio,
  languages.typescript,
  languages.csharp,
  libraries.dotnet,
  libraries.aspnet,
  languages.nodejs,
  uiFrameworks.angular,
  styling.angularMaterial,
  styling.scss,
  testing.cypress,
  testing.jest,
  databases.mongodb,
  api.graphql,
  cloud.azure,
  cloud.aws,
  authentication.msal,
  libraries.nx,
  libraries.apollo,
  tools.jira,
  tools.confluence,
  buildTools.webpack,
  buildTools.vite,
  container.docker,
  container.terraform,
];

export const skillsForCtream = [
  languages.typescript,
  uiFrameworks.react,
  uiFrameworks.nextjs,
  languages.nodejs,
  styling.mui,
  api.websocket,
  languages.python,
  libraries.flask,
  cloud.aws,
  ide.vscode,
  styling.styled,
  libraries.reactQuery,
  buildTools.vite,
];

export const skillsForAtis = [
  languages.typescript,
  uiFrameworks.react,
  languages.nodejs,
  testing.cypress,
  styling.mui,
  libraries.reactQuery,
  ide.vscode,
  api.openapi,
  libraries.nx,
  libraries.leaflet,
  libraries.recharts,
  cicd.jenkins,
  libraries.reactBeautifulDnd,
  buildTools.vite,
];

export const skillsForHeidelbergCement = [
  languages.typescript,
  languages.csharp,
  libraries.dotnet,
  languages.nodejs,
  uiFrameworks.react,
  libraries.redux,
  testing.cypress,
  testing.jest,
  testing.testingLibrary,
  styling.mui,
  libraries.reactQuery,
  ide.vscode,
  cloud.azure,
  tools.confluence,
  tools.jira,
  testing.xRay,
  versionControl.gitlab,
  webserver.nginx,
  buildTools.webpack,
];

export const skillsForKlarsolar = [
  languages.typescript,
  languages.go,
  uiFrameworks.angular,
  languages.nodejs,
  styling.angularMaterial,
  styling.tailwind,
  api.graphql,
  libraries.apollo,
  ide.vscode,
  container.kubernetes,
  container.helm,
  versionControl.github,
  buildTools.webpack,
];

export const skillsForSeeburger = [
  languages.java,
  libraries.spring,
  languages.nodejs,
  api.openapi,
  ide.intellij,
  ide.vscode,
  languages.typescript,
  uiFrameworks.react,
  libraries.redux,
  testing.testingLibrary,
  testing.jest,
  styling.mui,
  libraries.agGrid,
  container.kubernetes,
  container.helm,
  tools.jira,
  tools.confluence,
  versionControl.gerrit,
  buildTools.webpack,
];

export const skillsForTeamviewer = [
  libraries.knockoutJs,
  languages.typescript,
  languages.nodejs,
  buildTools.webpack,
  languages.csharp,
  libraries.dotnet,
  ide.visualStudio,
  ide.vscode,
  versionControl.bitbucket,
  tools.jira,
  tools.confluence,
];

export const skillsForProctorAndGamble = [
  ide.vscode,
  languages.typescript,
  languages.php,
  languages.nodejs,
  libraries.laravel,
  uiFrameworks.vue,
  buildTools.webpack,
  languages.javascript,
  databases.sql,
  versionControl.bitbucket,
  tools.jira,
  tools.confluence,
];

export const skillsForDaimler = [
  ide.vscode,
  languages.typescript,
  uiFrameworks.react,
  libraries.redux,
  testing.jest,
  buildTools.webpack,
  languages.nodejs,
  databases.sql,
  container.docker,
  api.rest,
  api.openapi,
  tools.jira,
  tools.confluence,
  container.kubernetes,
  container.helm,
  versionControl.github,
  libraries.reselect,
  libraries.immutablejs,
  webserver.traefik,
  libraries.sequelize,
];

export const skillsForGameforge = [
  languages.javascript,
  uiFrameworks.angular,
  uiFrameworks.react,
  libraries.redux,
  styling.scss,
  api.rest,
  container.docker,
  container.kubernetes,
  container.helm,
  languages.nodejs,
  languages.go,
  versionControl.bitbucket,
  tools.jira,
  tools.confluence,
  buildTools.webpack,
  api.openapi,
];

export const skillsForTimify = [
  languages.javascript,
  languages.nodejs,
  databases.mongodb,
  libraries.hapi,
  versionControl.github,
  tools.jira,
  tools.confluence,
  buildTools.webpack,
];

export const skillsForCybermanufaktur = [
  languages.javascript,
  languages.go,
  uiFrameworks.angular,
  languages.nodejs,
  languages.python,
  ide.intellij,
  libraries.jquery,
  languages.php,
  versionControl.bitbucket,
  tools.jira,
  tools.confluence,
  tools.wordpress,
  buildTools.webpack,
];

export const skillsForArvato = [
  languages.java,
  ide.eclipse,
  buildTools.maven,
  testing.junit,
  tools.confluence,
  tools.jira,
  databases.sql,
  tools.sqlDeveloper,
  versionControl.svn,
  languages.groovy,
];

export const skillsForEc4u = [
  languages.javascript,
  languages.go,
  libraries.jquery,
  buildTools.maven,
  languages.php,
  languages.python,
  libraries.oracleAdf,
  testing.selenium,
  tools.soapUI,
  ide.intellij,
  databases.sql,
  tools.sqlDeveloper,
  languages.java,
  tools.oracleSoaSuite,
  libraries.cordova,
  api.rest,
  tools.jira,
  tools.confluence,
];

export const skillsForJestRunner = [
  languages.typescript,
  languages.nodejs,
  ide.vscode,
  versionControl.github,
  testing.jest,
  buildTools.babel,
];

export const skillsForSendToKodi = [
  languages.python,
  languages.swift,
  languages.typescript,
  uiFrameworks.react,
  versionControl.github,
];

export const skillsForReactTrack = [
  languages.typescript,
  uiFrameworks.react,
  versionControl.github,
  libraries.apollo,
  api.graphql,
  styling.scss,
  styling.bootstrap,
  libraries.recharts,
  languages.nodejs,
  databases.lowdb,
  container.docker,
];
