import {
  authentication,
  buildTools,
  databases,
  ide,
  integration,
  languages,
  libraries,
  api,
  styling,
  testing,
  tools,
  webserver,
  cicd,
} from "./technologies";

export const skillsForDHL = [
  languages.typescript,
  languages.java,
  databases.sql,
  libraries.react,
  libraries.reactQuery,
  libraries.angular,
  styling.primeNg,
  libraries.spring,
  testing.jest,
  testing.playwright,
  testing.selenium,
  styling.emotion,
  api.rest,
  api.openapi,
  integration.azure,
  integration.docker,
  tools.jira,
  tools.confluence,
  ide.intellij,
  integration.github,
  integration.jenkins,
  integration.githubActions,
  webserver.nginx,
  cicd.jenkins,
  cicd.githubActions
]

export const skillsForJLA = [
  languages.typescript,
  languages.python,
  libraries.react,
  libraries.fastApi,
  api.rest,
  libraries.reactQuery,
  databases.postGresSql,
  integration.azure,
  authentication.msal,
  ide.vscode,
  api.openapi,
  integration.docker,
]

export const skillsForRwe = [
  ide.vscode,
  ide.visualStudio,
  languages.typescript,
  languages.csharp,
  libraries.angular,
  styling.angularMaterial,
  styling.scss,
  testing.cypress,
  testing.jest,
  databases.mongodb,
  api.graphql,
  integration.azure,
  integration.aws,
  authentication.msal,
  libraries.nx,
  libraries.apollo,
  tools.jira,
  tools.confluence,
];

export const skillsForCtream = [
  languages.typescript,
  libraries.react,
  libraries.nextjs,
  styling.mui,
  api.websocket,
  languages.python,
  libraries.flask,
  integration.aws,
  ide.vscode,
  styling.styled,
  libraries.reactQuery,
];

export const skillsForAtis = [
  languages.typescript,
  libraries.react,
  testing.cypress,
  styling.mui,
  libraries.reactQuery,
  ide.vscode,
  api.openapi,
  libraries.nx,
  libraries.leaflet,
  libraries.recharts,
  integration.jenkins,
  libraries.reactBeautifulDnd,
];

export const skillsForHeidelbergCement = [
  languages.typescript,
  libraries.react,
  libraries.redux,
  testing.cypress,
  testing.jest,
  testing.testingLibrary,
  styling.mui,
  libraries.reactQuery,
  ide.vscode,
  integration.azure,
  tools.confluence,
  tools.jira,
  testing.xRay,
  integration.gitlab,
  webserver.nginx,
];

export const skillsForKlarsolar = [
  languages.typescript,
  languages.go,
  libraries.angular,
  styling.angularMaterial,
  styling.tailwind,
  api.graphql,
  libraries.apollo,
  ide.vscode,
  integration.github,
];

export const skillsForSeeburger = [
  languages.java,
  libraries.spring,
  api.openapi,
  ide.intellij,
  ide.vscode,
  languages.typescript,
  libraries.react,
  libraries.redux,
  testing.testingLibrary,
  testing.jest,
  styling.mui,
  libraries.agGrid,
  tools.jira,
  tools.confluence,
  integration.gerrit,
];

export const skillsForTeamviewer = [
  libraries.knockoutJs,
  languages.typescript,
  buildTools.webpack,
  languages.csharp,
  ide.visualStudio,
  ide.vscode,
  integration.bitbucket,
  tools.jira,
  tools.confluence,
];

export const skillsForProctorAndGamble = [
  ide.vscode,
  languages.typescript,
  languages.php,
  libraries.laravel,
  libraries.vue,
  buildTools.webpack,
  languages.javascript,
  databases.sql,
  integration.bitbucket,
  tools.jira,
  tools.confluence,
];

export const skillsForDaimler = [
  ide.vscode,
  languages.typescript,
  libraries.react,
  libraries.redux,
  testing.jest,
  buildTools.webpack,
  languages.nodejs,
  databases.sql,
  integration.docker,
  api.rest,
  api.openapi,
  tools.jira,
  tools.confluence,
  integration.github,
  libraries.reselect,
  libraries.immutablejs,
  integration.traefik,
  libraries.sequelize,
];

export const skillsForGameforge = [
  languages.javascript,
  libraries.angular,
  libraries.react,
  libraries.redux,
  styling.scss,
  api.rest,
  integration.docker,
  integration.kubernetes,
  languages.nodejs,
  languages.go,
  integration.bitbucket,
  tools.jira,
  tools.confluence,
  buildTools.webpack,
  api.openapi,
];

export const skillsForTimify = [
  languages.javascript,
  languages.nodejs,
  databases.mongodb,
  libraries.hapi,
  integration.github,
  tools.jira,
  tools.confluence,
];

export const skillsForCybermanufaktur = [
  languages.javascript,
  languages.go,
  libraries.angular,
  languages.python,
  ide.intellij,
  libraries.jquery,
  languages.php,
  integration.bitbucket,
  tools.jira,
  tools.confluence,
  tools.wordpress,
];

export const skillsForArvato = [
  languages.java,
  ide.eclipse,
  buildTools.maven,
  testing.junit,
  tools.confluence,
  tools.jira,
  databases.sql,
  tools.sqlDeveloper,
  integration.svn,
  languages.groovy,
];

export const skillsForEc4u = [
  languages.javascript,
  languages.go,
  libraries.jquery,
  languages.php,
  languages.python,
  libraries.oracleAdf,
  testing.selenium,
  tools.soapUI,
  ide.intellij,
  databases.sql,
  tools.sqlDeveloper,
  languages.java,
  tools.oracleSoaSuite,
  libraries.cordova,
  api.rest,
  tools.jira,
  tools.confluence,
];

export const skillsForJestRunner = [
  languages.typescript,
  languages.nodejs,
  ide.vscode,
  integration.github,
  testing.jest,
  buildTools.babel,
];

export const skillsForSendToKodi = [
  languages.python,
  languages.swift,
  languages.typescript,
  libraries.react,
  integration.github,
];

export const skillsForReactTrack = [
  languages.typescript,
  libraries.react,
  integration.github,
  libraries.apollo,
  api.graphql,
  styling.scss,
  styling.bootstrap,
  libraries.recharts,
  languages.nodejs,
  databases.lowdb,
  integration.docker,
];
